version: 0.2

batch:
  build-list:
    - identifier: "Linux/X11"
      env:
        variables:
          GODOT_VERSION: "3.4.2"
          EXPORT_TYPE: "Linux/X11"
          EXPORT_FILE_NAME: "test.x86_64"
    - identifier: "Mac OSX"
      env:
        variables:
          GODOT_VERSION: "3.4.2"
          EXPORT_TYPE: "Mac OSX"
          EXPORT_FILE_NAME: "test.zip"
    # - identifier: "Android"
    #   env:
    #     variables:
    #       GODOT_VERSION: "3.4.2"
    #       EXPORT_TYPE: "Android"
    #       EXPORT_FILE_NAME: "android_debug.apk"

# env:
#   variables:
#     GODOT_VERSION: "3.4.2"

phases:
  install:
    commands:
      - .build-scripts/install_deps.sh
  pre_build:
    commands:
      - .build-scripts/lint.sh
  build:
    commands:
      - .build-scripts/init_godot.sh
      - mkdir -v -m 777 -p /root/var/builds/
      - godot -v --export $EXPORT_TYPE ~/var/builds/$EXPORT_FILE_NAME

artifacts:
  files:
    - '/root/var/builds/*'
  name: project-$(date +%Y-%m-%d)
  discard-paths: yes
